dist: trusty
sudo: required
env:
  global:
    - DISPLAY=:99.0
    - PYTEST_ADDOPTS="--verbose --instafail"
    - FF_ESR_BINARY=$HOME/firefox-latest-esr/firefox/firefox-bin
    - FF_NIGHTLY_BINARY=$HOME/firefox-latest-nightly/firefox/firefox-bin
git:
  depth: 10

_bindings:
  java: &java
    language: java
    jdk: oraclejdk8
  python: &python
    language: python
    python: "2.7"
  ruby: &ruby
    language: ruby
    rvm: 2.0.0-p648
    jdk: oraclejdk8

_browsers:
  firefox: &firefox-latest
    addons:
      firefox: latest
  firefox-esr: &firefox-esr
    addons:
      firefox: latest-esr
  firefox-nightly: &firefox-nightly
    addons:
      firefox: latest-nightly
  chrome: &chrome
    addons:
      apt:
        packages:
          - google-chrome-stable

cache:
  directories:
    - buck-out
    - build

before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh

jobs:
  include:
    - stage: small-tests
      script: ./go calcdeps && ./buckw build selenium-server-standalone //java/client/test/org/openqa/selenium/{environment,testing}/... //java/client/test/org/openqa/selenium:"
      <<: *java
    - stage: test
      matrix:
        include:
          - env: "BUCK=test //java/client/test/org/openqa/selenium/remote:remote-driver-grid-tests"
          <<: *java
          -env: "BUCK=test //java/client/test/org/openqa/selenium:small-tests"
          <<: *java

notifications:
  email: false
  irc:
    channels:
      - secure: K+Wuro8Y/66zt9truTZuZzFmPqiGrFsH/sPzOBDK3+57mL6/vg2NoQCXOTq3U5RLdVKavlvZcm6+9nsNncVPRgzL7ORuW3BgLaBJis3lTA13AqlOnAbXcYytQEulVeWmvPipHFFFqaHs/z77lxm4fKwAAuBnK1f+mXKZDZR2hLo=
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
