dist: trusty
sudo: required
env:
  global:
    - DISPLAY=:99.0
    - PYTEST_ADDOPTS="--verbose --instafail"
    - FF_ESR_BINARY=$HOME/firefox-latest-esr/firefox/firefox-bin
    - FF_NIGHTLY_BINARY=$HOME/firefox-latest-nightly/firefox/firefox-bin
git:
  depth: 10

_bindings:
  java: &java
    language: java
    jdk: oraclejdk8
  python: &python
    language: python
    python: "2.7"
  ruby: &ruby
    language: ruby
    rvm: 2.0.0-p648
    jdk: oraclejdk8

_browsers:
  firefox: &firefox-latest
    addons:
      firefox: latest
  firefox-esr: &firefox-esr
    addons:
      firefox: latest-esr
  firefox-nightly: &firefox-nightly
    addons:
      firefox: latest-nightly
  chrome: &chrome
    addons:
      apt:
        packages:
          - google-chrome-stable

cache:
  directories:
    - buck-out/cache

jobs:
  include:
    - stage: prepare cache
      script: TASK=build ./scripts/travis/script.sh
      <<: *java
    - stage: test
      script: TASK=//javascript/atoms:atoms ./scripts/travis/script.sh
      <<: *java
    - stage: test
      script: TASK=//javascript/webdriver:all_js ./scripts/travis/script.sh
      <<: *java
    - stage: test
      script: TASK=//javascript/ie-driver:atoms ./scripts/travis/script.sh
      <<: *java
    - stage: test
      script: TASK=//javascript/chrome-driver:atoms ./scripts/travis/script.sh
      <<: *java
    - stage: test
      script: TASK="//javascript/android-atoms:atoms ios_driver" ./scripts/travis/script.sh
      <<: *java
    - stage: test
      script: TASK=//java/client/test/org/openqa/selenium/atoms:test:run ./scripts/travis/script.sh
      <<: *java
    - stage: test
      install: CHROME=1 ./scripts/travis/install.sh
      script: TASK="calcdeps //javascript/selenium-atoms:selenium-atoms-chrome:run" ./scripts/travis/script.sh
      <<: *java
      <<: *chrome
    - stage: test
      install: CHROME=1 ./scripts/travis/install.sh
      script: TASK="calcdeps //javascript/selenium-core:selenium-core-chrome:run" ./scripts/travis/script.sh
      <<: *java
      <<: *chrome
#    - env: CHROME=1 TASK="calcdeps //javascript/atoms:atoms-chrome:run"
#      <<: *java
#      <<: *chrome
    - stage: test
      install: CHROME=1 ./scripts/travis/install.sh
      script: TASK="calcdeps //javascript/webdriver:webdriver-chrome:run" ./scripts/travis/script.sh
      <<: *java
      <<: *chrome
    - stage: test
      install: MARIONETTE=1 ./scripts/travis/install.sh
      script: TASK="calcdeps //javascript/atoms:atoms-firefox:run" ./scripts/travis/script.sh
      <<: *java
      <<: *firefox-latest
    - stage: test
      install: MARIONETTE=1 ./scripts/travis/install.sh
      script: TASK="calcdeps //javascript/webdriver:webdriver-firefox:run" ./scripts/travis/script.sh
      <<: *java
      <<: *firefox-latest
    - stage: test
      install: MARIONETTE=1 ./scripts/travis/install.sh
      script: TASK="calcdeps //javascript/selenium-atoms:selenium-atoms-firefox:run" ./scripts/travis/script.sh
      <<: *java
      <<: *firefox-latest
    - stage: test
      install: MARIONETTE=1 ./scripts/travis/install.sh
      script: TASK="calcdeps //javascript/selenium-core:selenium-core-firefox:run" ./scripts/travis/script.sh
      <<: *java
      <<: *firefox-latest
    - stage: test
      script: TASK=//java/client/test/org/openqa/selenium/firefox:test-synthesized:run ./scripts/travis/script.sh
      <<: *java
      <<: *firefox-esr
    - stage: test
      install: MARIONETTE=1 ./scripts/travis/install.sh
      script: TASK=//java/client/test/org/openqa/selenium/firefox:marionette:run ./scripts/travis/script.sh
      <<: *java
      <<: *firefox-nightly
    - stage: test
      script: TASK=test_java_small_tests ./scripts/travis/script.sh
      <<: *java
    - stage: test
      install: MARIONETTE=1 ./scripts/travis/install.sh
      script: TASK=test_grid ./scripts/travis/script.sh
      <<: *java
      <<: *firefox-nightly
#    - env: CHROME=1 TASK=test_chrome
#      <<: *java
#      <<: *chrome
    - stage: test
      script: TASK=test_htmlunit ./scripts/travis/script.sh
      <<: *java
    - stage: test
      script: TASK=javadocs ./scripts/travis/script.sh
      <<: *java
    - stage: test
      env: TOXENV=flake8
      <<: *python
    - stage: test
      env: TOXENV=docs
      <<: *python
    - stage: test
      env: TOXENV=py27-unit
      <<: *python
    - stage: test
      env: CHROME=1 TOXENV=py27-chrome
      <<: *python
      <<: *chrome
    - stage: test
      env: TOXENV=py27-firefox
      <<: *python
      <<: *firefox-esr
    - stage: test
      env: TOXENV=py27-remote
      <<: *python
      <<: *firefox-esr
    - stage: test
      env: MARIONETTE=1 TOXENV=py27-marionette
      <<: *python
      <<: *firefox-nightly
    - stage: test
      env: TOXENV=flake8
      <<: *python
      python: 3.6
    - stage: test
      env: TOXENV=docs
      <<: *python
      python: 3.6
    - stage: test
      env: TOXENV=py36-unit
      <<: *python
      python: 3.6
    - stage: test
      env: CHROME=1 TOXENV=py36-chrome
      <<: *python
      <<: *chrome
      python: 3.6
    - stage: test
      env: TOXENV=py36-firefox
      <<: *python
      <<: *firefox-esr
      python: 3.6
    - stage: test
      env: TOXENV=py36-remote
      <<: *python
      <<: *firefox-esr
      python: 3.6
    - stage: test
      env: MARIONETTE=1 TOXENV=py36-marionette
      <<: *python
      <<: *firefox-nightly
      python: 3.6
    - stage: test
      env: TASK=//rb:unit-test
      <<: *ruby
    - stage: test
      env: CHROME=1 TASK=//rb:chrome-test
      <<: *ruby
      <<: *chrome
    - stage: test
      env: MARIONETTE=1 TASK=//rb:firefox-test
      <<: *ruby
      <<: *firefox-latest
    - stage: test
      env: TASK=//rb:ff-esr-test
      <<: *ruby
      <<: *firefox-esr
    - stage: test
      env: CHROME=1 TASK=//rb:remote-chrome-test
      <<: *ruby
      <<: *chrome
    - stage: test
      env: MARIONETTE=1 TASK=//rb:remote-firefox-test
      <<: *ruby
      <<: *firefox-latest
    - stage: test
      env: TASK=//rb:remote-ff-esr-test
      <<: *ruby
      <<: *firefox-esr
    - stage: test
      env: TASK=//rb:docs
      <<: *ruby
    - stage: test
      env: TASK=//rb:lint
      <<: *ruby
before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh
notifications:
  email: false
  irc:
    channels:
      - secure: K+Wuro8Y/66zt9truTZuZzFmPqiGrFsH/sPzOBDK3+57mL6/vg2NoQCXOTq3U5RLdVKavlvZcm6+9nsNncVPRgzL7ORuW3BgLaBJis3lTA13AqlOnAbXcYytQEulVeWmvPipHFFFqaHs/z77lxm4fKwAAuBnK1f+mXKZDZR2hLo=
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
