dist: trusty
sudo: required
env:
  global:
    - DISPLAY=:99.0
    - PYTEST_ADDOPTS="--verbose --instafail"
    - FF_ESR_BINARY=$HOME/firefox-latest-esr/firefox/firefox-bin
    - FF_NIGHTLY_BINARY=$HOME/firefox-latest-nightly/firefox/firefox-bin
git:
  depth: 10

_bindings:
  java: &java
    language: java
    jdk: oraclejdk8
  python: &python
    language: python
    python: "2.7"
  ruby: &ruby
    language: ruby
    rvm: 2.0.0-p648
    jdk: oraclejdk8

_browsers:
  firefox: &firefox-latest
    before_script:
      - ./scripts/travis/before_script.sh
      - export GECKODRIVER_DOWNLOAD=`curl -s 'https://api.github.com/repos/mozilla/geckodriver/releases/latest' | python -c "import sys, json; r = json.load(sys.stdin); print([a for a in r['assets'] if 'linux64' in a['name']][0]['browser_download_url']);"`
      - curl -L -o geckodriver.tar.gz $GECKODRIVER_DOWNLOAD
      - gunzip -c geckodriver.tar.gz | tar xopf -
      - chmod +x geckodriver && sudo mv geckodriver /usr/local/bin
    addons:
      firefox: latest
  firefox-esr: &firefox-esr
    addons:
      firefox: latest-esr
  firefox-nightly: &firefox-nightly
    addons:
      firefox: latest-nightly
  chrome: &chrome
    before_script:
      - ./scripts/travis/before_script.sh
      - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
      - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      - unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
    addons:
      apt:
        packages:
          - google-chrome-stable

cache:
  directories:
    - buck-out
    - build

before_install: ./scripts/travis/before_install.sh
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh

jobs:
  include:
    - stage: warm cache
      before_script:
      script: ./go calcdeps && ./buckw build selenium-server-standalone //java/client/test/org/openqa/selenium/{environment,testing}/... "//java/client/test/org/openqa/selenium:"
      <<: *java
    - stage: test
      script: xdpyinfo; echo $PATH && echo $DISPLAY && ./buckw test //java/client/test/org/openqa/selenium:small-tests
      <<: *java
      <<: *chrome

notifications:
  email: false
  irc:
    channels:
      - secure: K+Wuro8Y/66zt9truTZuZzFmPqiGrFsH/sPzOBDK3+57mL6/vg2NoQCXOTq3U5RLdVKavlvZcm6+9nsNncVPRgzL7ORuW3BgLaBJis3lTA13AqlOnAbXcYytQEulVeWmvPipHFFFqaHs/z77lxm4fKwAAuBnK1f+mXKZDZR2hLo=
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
